//! Strict-Transport-Security on HTTPS responses (RFC 6797).

use async_trait::async_trait;
use http::{header::STRICT_TRANSPORT_SECURITY, HeaderValue};
use pingora_core::modules::http::{HttpModule, HttpModuleBuilder, Module};
use pingora_http::ResponseHeader;
use std::any::Any;

/// Adds a site's policy to every response of a request that names it over
/// HTTPS, whether proxied or generated by the gateway.
#[derive(Default)]
pub(crate) struct StrictTransport {
    pub header: Option<HeaderValue>,
}

#[async_trait]
impl HttpModule for StrictTransport {
    async fn response_header_filter(
        &mut self,
        response: &mut ResponseHeader,
        _end_of_stream: bool,
    ) -> pingora_core::Result<()> {
        if let Some(value) = &self.header {
            response.insert_header(STRICT_TRANSPORT_SECURITY, value.clone())?;
        }
        Ok(())
    }

    fn as_any(&self) -> &dyn Any {
        self
    }

    fn as_any_mut(&mut self) -> &mut dyn Any {
        self
    }
}

pub(crate) struct StrictTransportBuilder;

impl HttpModuleBuilder for StrictTransportBuilder {
    fn init(&self) -> Module {
        Box::new(StrictTransport::default())
    }
}
