//! Responses generated by the gateway instead of an upstream.

use bytes::Bytes;
use http::{header, HeaderName, Method};
use pingora_http::ResponseHeader;
use pingora_proxy::Session;

/// RFC 9110 §6.4.1: these statuses never carry content.
fn has_content(status: u16) -> bool {
    !matches!(status, 100..=199 | 204 | 304)
}

pub(crate) async fn send(
    session: &mut Session,
    status: u16,
    headers: &[(HeaderName, &str)],
    body: Bytes,
) -> pingora_core::Result<()> {
    let mut response = ResponseHeader::build(status, Some(headers.len() + 1))?;
    for (name, value) in headers {
        response.insert_header(name.clone(), *value)?;
    }
    if has_content(status) {
        response.insert_header(header::CONTENT_LENGTH, body.len().to_string())?;
    }
    let send_body =
        has_content(status) && !body.is_empty() && session.req_header().method != Method::HEAD;
    session
        .write_response_header(Box::new(response), !send_body)
        .await?;
    if send_body {
        session.write_response_body(Some(body), true).await?;
    }
    Ok(())
}

/// A short diagnostic for the client; never cached.
pub(crate) async fn plain(
    session: &mut Session,
    status: u16,
    message: &str,
    extra: &[(HeaderName, &str)],
) -> pingora_core::Result<()> {
    let mut headers = vec![
        (header::CONTENT_TYPE, "text/plain; charset=utf-8"),
        (header::CACHE_CONTROL, "no-store"),
    ];
    headers.extend(extra.iter().cloned());
    send(
        session,
        status,
        &headers,
        Bytes::from(format!("{message}\n")),
    )
    .await
}

pub(crate) async fn redirect(
    session: &mut Session,
    status: u16,
    location: &str,
) -> pingora_core::Result<()> {
    send(
        session,
        status,
        &[(header::LOCATION, location)],
        Bytes::new(),
    )
    .await
}
