[package]
name = "panel-bootstrap"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
async-nats.workspace = true
chrono.workspace = true
panel-context.workspace = true
panel-control-runtime.workspace = true
panel-errors.workspace = true
panel-jetstream.workspace = true
panel-pki.workspace = true
panel-service.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
panel-jetstream = { workspace = true, features = ["test-support"] }
