//! Public HTTP schema assembled from endpoint definitions and shared conventions.

use crate::contract::*;
use conventions::HttpConventions;
use utoipa::OpenApi;

mod conventions;
#[cfg(test)]
mod tests;

#[derive(OpenApi)]
#[openapi(
    info(title = "Pingora Panel API", version = "v1"),
    paths(
        crate::routes::validate, crate::routes::prepare, crate::routes::activate, crate::routes::abort,
        crate::routes::status, crate::routes::receipt, crate::routes::services, crate::routes::openapi,
        crate::configuration::list_sites, crate::configuration::create_site, crate::configuration::site_summary,
        crate::configuration::export_sites, crate::configuration::import_sites, crate::configuration::batch_sites,
        crate::configuration::get_site, crate::configuration::replace_site, crate::configuration::delete_site,
        crate::configuration::enable_site, crate::configuration::disable_site, crate::configuration::favorite_site,
        crate::configuration::unfavorite_site, crate::configuration::restore_site, crate::configuration::clone_site,
        crate::configuration::add_domains, crate::configuration::replace_domain, crate::configuration::remove_domain,
        crate::configuration::list_routes, crate::configuration::create_route, crate::configuration::reorder_routes,
        crate::configuration::get_route, crate::configuration::replace_route, crate::configuration::delete_route,
        crate::configuration::list_domains, crate::configuration::check_domains,
        crate::configuration::list_upstreams, crate::configuration::create_upstream, crate::configuration::get_upstream,
        crate::configuration::replace_upstream, crate::configuration::delete_upstream,
        crate::configuration::add_node, crate::configuration::replace_node, crate::configuration::delete_node,
        crate::configuration::list_listeners, crate::configuration::get_listener, crate::configuration::put_listener,
        crate::configuration::delete_listener, crate::configuration::list_tls_profiles,
        crate::configuration::get_tls_profile, crate::configuration::put_tls_profile,
        crate::configuration::delete_tls_profile, crate::configuration::list_security_policies,
        crate::configuration::get_security_policy, crate::configuration::put_security_policy,
        crate::configuration::delete_security_policy, crate::configuration::draft, crate::configuration::validation,
        crate::configuration::apply,
        crate::language::source, crate::language::replace_source, crate::language::check,
        crate::language::format, crate::language::schema,
        crate::traffic::traffic_summary,
        crate::traffic::traffic_series,
        crate::logs::search_logs, crate::logs::download_logs, crate::logs::tail_logs,
        crate::logs::delete_logs, crate::logs::list_log_deletions,
        crate::host::host_summary,
        crate::host_agent::host_agent,
        crate::host_agent::host_directories,
        crate::host_agent::host_listeners,
        crate::host_agent::gateway_service,
        crate::host_agent::change_gateway_service,
        crate::containers::list_engines,
        crate::containers::enable_engine,
        crate::containers::disable_engine,
        crate::containers::list_containers,
        crate::containers::inspect_container,
        crate::containers::act_on_container,
        crate::containers::remove_container,
        crate::containers::container_logs,
        crate::containers::tail_container_logs,
        crate::containers::list_container_stats,
        crate::containers::container_stats,
        crate::images::list_images,
        crate::images::inspect_image,
        crate::images::remove_image,
        crate::alerts::list_alert_rules, crate::alerts::put_alert_rule,
        crate::alerts::delete_alert_rule, crate::alerts::list_alert_channels,
        crate::alerts::create_alert_channel, crate::alerts::rotate_alert_channel,
        crate::alerts::delete_alert_channel, crate::alerts::test_alert_channel,
        crate::alerts::list_alert_notifications,
        crate::audit::list_audit_events,
        crate::audit::get_audit_event,
        crate::audit::verify_audit_events,
        crate::certificates::list_certificates, crate::certificates::create_certificate,
        crate::certificates::get_certificate, crate::certificates::replace_certificate,
        crate::certificates::delete_certificate, crate::certificates::certificate_coverage,
        crate::certificates::inspect_certificate, crate::tls_checks::check_tls,
        crate::acme::list_acme_accounts, crate::acme::create_acme_account,
        crate::acme::get_acme_account, crate::acme::delete_acme_account,
        crate::acme::list_automatic_certificates, crate::acme::create_automatic_certificate,
        crate::acme::get_automatic_certificate, crate::acme::renew_automatic_certificate,
        crate::acme::delete_automatic_certificate,
        crate::acme::list_dns_providers, crate::acme::create_dns_provider,
        crate::acme::get_dns_provider, crate::acme::update_dns_provider,
        crate::acme::delete_dns_provider,
        crate::language::ast,
        crate::language::explain,
        crate::language::ir,
        crate::language::import_nginx, crate::language::plan, crate::language::dry_run,
        crate::language::list_revisions, crate::language::get_revision, crate::language::diff_revision,
        crate::language::restore_revision, crate::language::note_revision,
        crate::gateway_runtime::data_plane, crate::gateway_runtime::reload, crate::gateway_runtime::workers,
        crate::gateway_runtime::shutdown, crate::gateway_runtime::upstream_health, crate::gateway_runtime::drain,
        crate::gateway_runtime::file_checks,
        crate::gateway_runtime::restore,
        crate::identity::setup_status, crate::identity::setup, crate::identity::login,
        crate::identity::session, crate::identity::logout, crate::identity::permissions,
        crate::identity::change_password, crate::identity::own_sessions,
        crate::identity::end_own_session, crate::identity::own_tokens,
        crate::identity::create_token, crate::identity::revoke_own_token,
        crate::identity::list_accounts, crate::identity::create_account,
        crate::identity::get_account, crate::identity::update_account,
        crate::identity::reset_password, crate::identity::account_sessions,
        crate::identity::end_account_session, crate::identity::account_tokens,
        crate::identity::issue_token, crate::grants::list_grants,
        crate::grants::create_grant, crate::grants::delete_grant,
        crate::identity::revoke_account_token, crate::identity::list_roles,
        crate::identity::create_role, crate::identity::replace_role, crate::identity::delete_role,
        crate::identity::end_other_sessions, crate::identity::end_account_sessions,
        crate::identity::rotate_token, crate::sign_in::list_identity_providers, crate::sign_in::get_identity_provider,
        crate::sign_in::put_identity_provider, crate::sign_in::delete_identity_provider, crate::sign_in::sign_in_options,
        crate::sign_in::start_sign_in, crate::sign_in::finish_sign_in,
        crate::sign_in::get_sign_in_policy, crate::sign_in::put_sign_in_policy,
        crate::approvals::list_approval_policies, crate::approvals::get_approval_policy,
        crate::approvals::put_approval_policy, crate::approvals::delete_approval_policy,
        crate::approvals::list_approval_requests, crate::approvals::get_approval_request,
        crate::approvals::approve_request, crate::approvals::reject_request, crate::approvals::revoke_approval,
        crate::approvals::withdraw_request, crate::workload::list_workload_identities,
        crate::workload::get_workload_identity, crate::workload::put_workload_identity,
        crate::workload::delete_workload_identity, crate::workload::exchange_workload_token
    ),
    tags(
        (name = "configuration", description = "Sites, domains, routes, upstreams, listeners and TLS profiles, edited as a draft and applied to the gateway"),
        (name = "approvals", description = "Policies that ask other people to approve covered changes before they are applied, and the requests they open"),
        (name = "gateway", description = "The running gateway: data plane, workers, shutdown and upstream health"),
        (name = "traffic", description = "What the gateway served, from its metrics: requests, status classes, latency, traffic, connections, upstreams and routes"),
        (name = "logs", description = "The gateway's access and error logs: searched, followed as they arrive, downloaded and deleted"),
        (name = "host", description = "The host the gateway runs on: CPU, memory, filesystems, load, network and system"),
        (name = "containers", description = "The Docker and Podman engines the host agent reaches and what runs on them"),
        (name = "alerts", description = "Rules that fire on the gateway's metrics, the signed webhooks they notify and the notifications sent"),
        (name = "audit", description = "Every change and every refused or failed attempt, in a tamper-evident hash chain"),
        (name = "certificates", description = "Server certificates whose private keys stay sealed with the panel and are delivered to the gateway, and the ACME accounts and automatic certificates that keep some of them issued and renewed"),
        (name = "identity", description = "Setup, login sessions, API tokens, accounts, roles and permissions")
    ),
    modifiers(&HttpConventions),
    components(schemas(
        SnapshotEnvelope,
        ActivateRequest,
        AbortRequest,
        AbortResponse,
        ValidationResponse,
        PreparedResponse,
        ActivatedResponse,
        GatewayStatusResponse,
        IdempotencyReceiptPendingResponse,
        IdempotencyReceiptResponse,
        ReceiptOutcomeResponse,
        ServiceListingResponse,
        ServiceInstanceResponse,
        ProtocolSupportResponse,
        CapabilityResponse,
        ProblemDetails,
        panel_config_model::SiteSort,
        panel_config_model::SiteStatus,
        panel_config_model::SiteKind,
        crate::logs::LogTailMessage,
        crate::host_agent::GatewayServiceActionName,
        crate::containers::ContainerActionName,
        crate::containers::ContainerLogTailMessage
    ))
)]
pub struct ApiDoc;
