[package]
name = "gatewayd"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
futures-util.workspace = true
gateway-grpc.workspace = true
gateway-pingora.workspace = true
gateway-proto-codec.workspace = true
panel-api.workspace = true
panel-application.workspace = true
panel-context.workspace = true
panel-contracts.workspace = true
panel-domain.workspace = true
panel-engine.workspace = true
panel-errors.workspace = true
panel-gateway-runtime.workspace = true
panel-ir.workspace = true
panel-pki.workspace = true
panel-tls.workspace = true
prost-types.workspace = true
serde.workspace = true
serde_json.workspace = true
snapshot-store-fs.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tonic-health.workspace = true
tonic.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[dev-dependencies]
gateway-grpc-client.workspace = true
panel-config-json.workspace = true
panel-health.workspace = true
panel-persistence-memory.workspace = true
reqwest.workspace = true
rustls.workspace = true
tokio-stream.workspace = true
uuid.workspace = true
