[package]
name = "ops-grpc-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
panel-application.workspace = true
panel-contracts.workspace = true
panel-errors.workspace = true
panel-service.workspace = true
prost-types.workspace = true
tokio-stream.workspace = true
tonic.workspace = true

[dev-dependencies]
tokio.workspace = true
