[package]
name = "observability-service"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
panel-control-runtime.workspace = true
panel-errors.workspace = true
panel-platform.workspace = true
panel-postgres.workspace = true
panel-service.workspace = true
