[package]
name = "identity-oidc"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
panel-errors.workspace = true
ring.workspace = true
serde.workspace = true
serde_json.workspace = true
