[package]
name = "gateway-grpc-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
gateway-grpc.workspace = true
panel-application.workspace = true
panel-contracts.workspace = true
panel-domain.workspace = true
panel-errors.workspace = true
panel-ir.workspace = true
tonic.workspace = true
