[package]
name = "panel-pki"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
getrandom.workspace = true
panel-context.workspace = true
panel-errors.workspace = true
pem.workspace = true
rcgen.workspace = true
rustls-pki-types.workspace = true
time.workspace = true
x509-parser.workspace = true

[dev-dependencies]
rustls-webpki.workspace = true
