[package]
name = "dns-rfc2136"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
hickory-proto.workspace = true
panel-acme.workspace = true
panel-errors.workspace = true
tokio = { workspace = true, features = ["io-util", "net"] }
zeroize.workspace = true

[dev-dependencies]
getrandom.workspace = true
hex.workspace = true
tokio = { workspace = true, features = ["io-util", "net", "macros", "rt-multi-thread"] }
